CREATE TABLE IF NOT EXISTS EMPRESAS (
  EMP_CODIGO SERIAL PRIMARY KEY,
  EMP_CODIGOFILIAL VARCHAR(2),
  EMP_NOMEFANTASIA VARCHAR(60),
  EMP_RAZAOSOCIAL VARCHAR(60),
  EMP_TELEFONE VARCHAR(20),
  EMP_FAX VARCHAR(20),
  EMP_CGC VARCHAR(18),
  EMP_IE VARCHAR(18),
  EMP_ENDERECO VARCHAR(60),
  EMP_COMPLENDERECO VARCHAR(60),
  EMP_BAIRRO VARCHAR(20),
  EMP_CIDADE VARCHAR(20),
  EMP_ESTADO VARCHAR(2),
  EMP_CEP VARCHAR(11),
  EMP_SUFRAMA VARCHAR(20),
  EMP_IM VARCHAR(20),
  EMP_VLR_UNITARIOOVO DECIMAL(18, 3)
  );