CREATE TABLE IF NOT EXISTS EMPRESAS (
  EMP_CODIGO SERIAL PRIMARY KEY,
  EMP_CODIGOFILIAL VARCHAR(2),
  EMP_NOMEFANTASIA VARCHAR(60),
  EMP_RAZAOSOCIAL VARCHAR(60),
  EMP_TELEFONE VARCHAR(20),
  EMP_FAX VARCHAR(20),
  EMP_CGC VARCHAR(18),
  EMP_IE VARCHAR(18),
  EMP_ENDERECO VARCHAR(60),
  EMP_COMPLENDERECO VARCHAR(60),
  EMP_BAIRRO VARCHAR(20),
  EMP_CIDADE VARCHAR(20),
  EMP_ESTADO VARCHAR(2),
  EMP_CEP VARCHAR(11),
  EMP_SUFRAMA VARCHAR(20),
  EMP_IM VARCHAR(20),
  EMP_VLR_UNITARIOOVO DECIMAL(18, 3)
  );
  
CREATE TABLE IF NOT EXISTS LOCALIZACAO (
    LOC_CODIGO SERIAL PRIMARY KEY,
    EMP_CODIGO INTEGER,
    LOC_DESCRICAO VARCHAR(30),
    LOC_PODESOMAR VARCHAR(1)
);

CREATE TABLE IF NOT EXISTS TIPOPRODUTO (
  TPR_CODIGO SERIAL PRIMARY KEY,
  EMP_CODIGO INTEGER,
  TPR_DESCRICAO VARCHAR(60),
  TPR_USERCAD VARCHAR(20),
  TPR_DATACAD DATE,
  TPR_HORACAD TIME,
  TPR_EXIBENOORCAMENTO VARCHAR(1)
);

CREATE TABLE IF NOT EXISTS GRUPOS (
  GRU_CODIGO SERIAL PRIMARY KEY,
  EMP_CODIGO INTEGER,
  GRU_DESCRICAO VARCHAR(30),
  GRU_COMISSAO DECIMAL(18, 2),
  GRU_DESCONTO DECIMAL(18, 2),
  GRU_FATORCIF DECIMAL(10, 3),
  GRU_FATORCUSTO DECIMAL(10, 3),
  GRU_FATORVAREJO DECIMAL(10, 3),
  GRU_FATORATACADO DECIMAL(10, 3),
 );

CREATE TABLE IF NOT EXISTS TIPOAVE (
  TAV_CODIGO SERIAL PRIMARY KEY,
  EMP_CODIGO INTEGER,
  TAV_DESCRICAO VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS TIPOCOR (
  TCR_CODIGO SERIAL PRIMARY KEY,
  EMP_CODIGO INTEGER,
  TCR_DESCRICAO VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS TIPOVACINA (
  TVC_CODIGO SERIAL PRIMARY KEY,
  EMP_CODIGO INTEGER,
  TVC_DESCRICAO VARCHAR(60),
  TVC_USERCAD VARCHAR(20),
  TVC_DATACAD DATE,
  TVC_HORACAD TIME
);

CREATE TABLE IF NOT EXISTS UNIDADEMEDIDA (
  UNM_CODIGO VARCHAR(3),
  EMP_CODIGO INTEGER,
  UNM_DESCRICAO VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS TIPOPADRAOAVE (
  TPA_SEMANA SERIAL PRIMARY KEY,
  EMP_CODIGO INTEGER,
  TAV_CODIGO INTEGER,
  TPA_VRL_PADRAO_MORTALIDADE DECIMAL(18, 3),
  TPA_VLR_PADRAO_PESOCORPORAL DECIMAL(18, 3),
  TPA_VLR_PADRAO_CONSUMORACAO DECIMAL(18, 3),
  TPA_VLR_PADRAO_OVOSPRODUZIDOS DECIMAL(18, 3),
  TPA_VLR_PADRAO_AVEALOJADA DECIMAL(18, 3),
  TPA_VLR_PADRAO_PESOOVO DECIMAL(18, 3),
  TPA_VLR_PADRAO_VIABILIDADE DECIMAL(18, 3),
  TPA_VLR_PADRAO_KCALAVEDIA DECIMAL(18, 3),
  TPA_VLR_PADRAO_KCALKG DECIMAL(18, 3),
  TPA_VLR_PADRAO_GAVEDIA DECIMAL(18, 3)
);

 CREATE TABLE IF NOT EXISTS FORNECEDOR (
    FOR_CODIGO SERIAL PRIMARY KEY,
    EMP_CODIGO SERIAL INTEGER,
    FOR_NOMEFANTASIA VARCHAR(60),
    FOR_RAZAOSOCIAL VARCHAR(60),
    FOR_CONTATO VARCHAR(30),
    FOR_CARGOCONTATO VARCHAR(30),
    FOR_SETORCONTATO VARCHAR(30),
    FOR_ENDERECO VARCHAR(60),
    FOR_BAIRRO VARCHAR(20),
    FOR_CIDADE VARCHAR(20),
    FOR_ESTADO VARCHAR(2),
    FOR_CEP VARCHAR(11),
    FOR_TELEFONE1 VARCHAR(20),
    FOR_TELEFONE2 VARCHAR(20),
    FOR_TELEFONE3 VARCHAR(20),
    FOR_FAX VARCHAR(20),
    FOR_CGC VARCHAR(18),
    FOR_CPF VARCHAR(18),
    FOR_IE VARCHAR(18),
    FOR_RG VARCHAR(18),
    FOR_EMAIL VARCHAR(60),
    FOR_HOMEPAGE VARCHAR(120),
    FOR_ULTIMACOMPRA DATE,
    FOR_DATAINCLUSAO DATE,
    FOR_PRAZODEENTREGA VARCHAR(20),
    FOR_CPG_CODIGO INTEGER,
    FOR_TPZ_CODIGO VARCHAR(1),
    FOR_TPP_CODIGO VARCHAR(1)
);

CREATE TABLE IF NOT EXISTS VENDEDOR (
  VDR_CODIGO SERIAL PRIMARY KEY,
  EMP_CODIGO INTEGER,
  VDR_NOMEDOVENDEDOR VARCHAR(60),
  VDR_CPF VARCHAR(18),
  VDR_PIS VARCHAR(28),
  VDR_RG VARCHAR(20),
  VDR_CARTEIRAPROF VARCHAR(20),
  VDR_SERIECARTEIRAPROF VARCHAR(20),
  VDR_UFCARTEIRAPROF VARCHAR(2),
  VDR_CARTEIRARESERVISTA VARCHAR(20),
  VDR_TITULOELEITOR VARCHAR(20),
  VDR_ZONA VARCHAR(10),
  VDR_SECAO VARCHAR(10),
  VDR_ENDERECO VARCHAR(60),
  VDR_COMPLENDERECO VARCHAR(60),
  VDR_BAIRRO VARCHAR(20),
  VDR_CIDADE VARCHAR(20),
  VDR_ESTADO VARCHAR(2),
  VDR_CEP VARCHAR(11),
  VDR_TELEFONE1 VARCHAR(20),
  VDR_TELEFONE2 VARCHAR(20),
  VDR_SEXO VARCHAR(1),
  VDR_DATANASCIMENTO DATE,
  VDR_SALARIO DECIMAL(18, 2),
  VDR_COMISSAO DECIMAL(18, 2),
  VDR_DESCONTOMAX DECIMAL(18, 2),
  VDR_EMAIL VARCHAR(120),
  VDR_DATACADASTRO DATE,
  VDR_SENHAPONTO VARCHAR(8),
  VDR_DATAADMISSAO DATE,
  VDR_COTAJAN DECIMAL(18, 2),
  VDR_COTAFEV DECIMAL(18, 2),
  VDR_COTAMAR DECIMAL(18, 2),
  VDR_COTAABR DECIMAL(18, 2),
  VDR_COTAMAI DECIMAL(18, 2),
  VDR_COTAJUN DECIMAL(18, 2),
  VDR_COTAJUL DECIMAL(18, 2),
  VDR_COTAAGO DECIMAL(18, 2),
  VDR_COTASET DECIMAL(18, 2),
  VDR_COTAOUT DECIMAL(18, 2),
  VDR_COTANOV DECIMAL(18, 2),
  VDR_COTADEZ DECIMAL(18, 2)
 );
 
CREATE TABLE IF NOT EXISTS GALPAO (
   GLP_CODIGO SERIAL PRIMARY KEY,
   EMP_CODIGO INTEGER,
   LOC_CODIGO INTEGER,
   GLP_DESCRICAO VARCHAR(60),
   GLP_USERCAD VARCHAR(20),
   GLP_DATACAD DATE,
   GLP_HORACAD TIME
);

CREATE TABLE IF NOT EXISTS CONTABANCARIA (
  CBA_CODIGO SERIAL PRIMARY KEY,
  EMP_CODIGO INTEGER,
  CBA_DESCRICAO VARCHAR(60),
  CBA_NUMEROCONTA VARCHAR(20),
  CBA_NUMEROAGENCIA VARCHAR(20),
  CBA_BCS_CODIGO INTEGER,
  CBA_TELEFONE VARCHAR(20),
  CBA_FAX VARCHAR(20),
  CBA_NOMECONTATO VARCHAR(30),
  CBA_SITUACAO VARCHAR(1),
  CBA_DATAABERTURA DATE,
  CBA_USERCAD VARCHAR(20),
  CBA_DATACAD DATE,
  CBA_HORACAD TIME,
  CBA_VLR_SALDO DECIMAL(18, 2),
  CBA_VLR_LIMITECREDITO DECIMAL(18, 2)
);

CREATE TABLE IF NOT EXISTS TIPOSITUACAORECEITAS (
  TSR_CODIGO SERIAL PRIMARY KEY,
  EMP_CODIGO INTEGER,
  TSR_DESCRICAO VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS PLANOCONTAS (
  PLC_CODIGO SERIAL PRIMARY KEY,
  EMP_CODIGO INTEGER,
  PLC_PLANO VARCHAR(19),
  PLC_DESCRICAO VARCHAR(60),
  PLC_NIVEL INTEGER,
  PLC_RECEBELANCAMENTO VARCHAR(1),
  PLC_NATUREZA VARCHAR(1),
  PLC_USERCAD VARCHAR(20),
  PLC_DATACAD DATE,
  PLC_HORACAD TIME,
  PLC_HISTORICOPADRAO VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS TIPODOCUMENTO (
  TDC_CODIGO SERIAL PRIMARY KEY,
  EMP_CODIGO INTEGER,
  TDC_DESCRICAO VARCHAR(60)
 );
 
CREATE TABLE IF NOT EXISTS TIPOMOTIVOBAIXA (
   TMB_CODIGO SERIAL PRIMARY KEY,
   EMP_CODIGO INTEGER,
   TMB_DESCRICAO VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS TIPOPESSOA (
  TPP_CODIGO SERIAL PRIMARY KEY,
  EMP_CODIGO VARCHAR(1),
  TPP_DESCRICAO VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS CLIENTE (
  CLI_CODIGO SERIAL PRIMARY KEY,
  EMP_CODIGO INTEGER,
  TPP_CODIGO VARCHAR(1),
  CLI_NOMEFANTASIA VARCHAR(60),
  CLI_RAZAOSOCIAL VARCHAR(60),
  CLI_CONTATO VARCHAR(60),
  CLI_DATANASCIMENTO DATE,
  CLI_ENDERECORES VARCHAR(60),
  CLI_PONTOREFERENCIA VARCHAR(100),
  CLI_BAIRRORES VARCHAR(20),
  CLI_CIDADERES VARCHAR(20),
  CLI_ESTADORES VARCHAR(2),
  CLI_CEPRES VARCHAR(11),
  CLI_TELEFONERES VARCHAR(20),
  CLI_FAX VARCHAR(20),
  CLI_CGC VARCHAR(18),
  CLI_IE VARCHAR(18),
  CLI_IM VARCHAR(18),
  CLI_RG VARCHAR(14),
  CLI_CPF VARCHAR(18),
  CLI_ULTIMACOMPRA DATE,
  CLI_EMAILRES VARCHAR(60),
  CLI_EMAILCOM VARCHAR(60),
  CLI_HOMEPAGE VARCHAR(60),
  CLI_NOMEEMPRESA VARCHAR(60),
  CLI_CARGONAEMPRESA VARCHAR(25),
  CLI_SETOREMPRESA VARCHAR(20),
  CLI_ENDERECOCOM VARCHAR(60),
  CLI_BAIRROCOM VARCHAR(30),
  CLI_TELEFONECOM VARCHAR(20),
  CLI_CIDADECOM VARCHAR(20),
  CLI_CEPCOM VARCHAR(11),
  CLI_ESTADOCOM VARCHAR(2),
  CLI_RENDA NUMERIC(18, 2),
  CLI_DEBITOS NUMERIC(18, 2),
  CLI_PRACA VARCHAR(30),
  CLI_MAIORCOMPRA NUMERIC(18, 2),
  CLI_NUMERODECOMPRAS SMALLINT,
  CLI_PRIMEIRACOMPRA DATE,
  CLI_CHEQUESDEVOLVIDOS SMALLINT,
  CLI_NUMEROPGATRASADOS SMALLINT,
  CLI_ETRANSPORTADORA VARCHAR(1),
  CLI_OBSERVACAO VARCHAR(200),
  CLI_VND_CODIGO INTEGER,
  CLI_VALORICMS NUMERIC(18, 2),
  CLI_RECOLHEICMS VARCHAR(1),
  CLI_CPG_CODIGO INTEGER,
  CLI_MESNASC SMALLINT,
  CLI_DIANASC SMALLINT,
  CLI_VLR_ULTIMACOMPRA NUMERIC(18, 2),
  CLI_VLR_TOTALCOMPRA NUMERIC(18, 2),
  CLI_BLOQUEADO VARCHAR(1),
  CLI_LIMITECREDITO NUMERIC(18, 2),
  CLI_VLR_TOTALDEBITOS NUMERIC(18, 2),
  CLI_VLR_TOTALCREDITO NUMERIC(18, 2)
 );
  
CREATE TABLE IF NOT EXISTS RECEITAS (
  RCT_CODIGO SERIAL PRIMARY KEY,
  RCT_NUMERODOCUMENTO VARCHAR(20),
  EMP_CODIGO INTEGER,
  RCT_CLI_CODIGO VARCHAR(8) ,
  VDR_CODIGO INTEGER,
  PLC_CODIGO INTEGER,
  TSR_CODIGO INTEGER,
  CBA_CODIGO INTEGER,
  TDC_CODIGO INTEGER,
  RCT_HISTORICOEMISSAO VARCHAR(120),
  RCT_DATAEMISSAO DATE,
  RCT_DATAVENCIMENTO DATE,
  RCT_DATAVENCIMENTOREAL DATE,
  RCT_DATAQUITACAO DATE,
  RCT_OBSERVACAO VARCHAR(120) ,
  RCT_VLR_DOCUMENTO DECIMAL(18, 2),
  RCT_VLR_DESCONTOMOE DECIMAL(18, 2),
  RCT_VLR_DESCONTOPER DECIMAL(18, 2),
  RCT_VLR_JUROSDIA DECIMAL(18, 2),
  RCT_VLR_MULTA DECIMAL(18, 2),
  RCT_VLR_QUITADO DECIMAL(18, 2),
  RCT_VLR_PENDENTE DECIMAL(18, 2),
  RCT_VLR_JUROSRECEBIDOS DECIMAL(18, 2),
  RCT_VLR_MULTARECEBIDOS DECIMAL(18, 2),
  RCT_VLR_DESCONTOSCONCEDIDOS DECIMAL(18, 2),
  RCT_VLR_DESPESASRECEBIDOS DECIMAL(18, 2)
 );
 
 CREATE TABLE IF NOT EXISTS RECEITASITEM (
   RCI_CODIGO SERIAL PRIMARY KEY,
   RCI_NUMERODOCUMENTO VARCHAR(20),
   RCT_CODIGO INTEGER,
   EMP_CODIGO INTEGER,
   TMB_CODIGO INTEGER,
   PLC_CODIGO INTEGER,
   CBA_CODIGO INTEGER,
   RCI_PARCELA INTEGER,
   RCI_DATAPAGAMENTO DATE,
   RCI_DATAVENCIMENTO DATE,
   RCI_COMPROVANTE VARCHAR(20),
   RCI_NATUREZA VARCHAR(1),
   RCI_HISTORICOBAIXA VARCHAR(60),
   RCI_VLR_VALORPAGO DECIMAL(18, 2),
   RCI_VLR_JUROS DECIMAL(18, 2),
   RCI_VLR_MULTAS DECIMAL(18, 2),
   RCI_VLR_DESCONTOMOE DECIMAL(18, 2),
   RCI_VLR_DESPESAS DECIMAL(18, 2),
   RCI_USERCAD VARCHAR(20),
   RCI_DATACAD DATE,
   RCI_HORACAD TIME
);